/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class TestJNI_JNICallCpp */

#ifndef _Included_TestJNI_JNICallCpp
#define _Included_TestJNI_JNICallCpp
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     TestJNI_JNICallCpp
	 * Method:    HannoTower
	 * Signature: (ICCC)V
	 */
	JNIEXPORT void JNICALL Java_TestJNI_JNICallCpp_HannoTower
	(JNIEnv *, jobject, jint, jchar, jchar, jchar);

	/*
	 * Class:     TestJNI_JNICallCpp
	 * Method:    HellCpp
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_TestJNI_JNICallCpp_HellCpp
	(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
